### ISSUE TITLE
how tf i run this

### ISSUE THREAD

**Issue by Hacker-Turbo** [petidecember/AnnoyMe#1]
rlly, where do i even start :v

**Comment by petidecember** [comment]
You will need to install nodejs and express and socket.io with npm, after that just `node lameprogram.js` in the cmd and the server should start on localhost:3000.
Originally i wrote this with a C# client but i dont have that uploaded or saved (i think) anywhere, still this is just a basic ping-pong messaging implementation using socket.io with a fancy html gui, so writing a client for this would be straightforward.

**Comment by petidecember** [comment]
I have updated the repository to include a basic python client.

**Comment by Hacker-Turbo** [comment]
thx bro, really helped :)

**Comment by petidecember** [comment]
You're welcome.
